### ISSUE TITLE
Create a cover block style variation that extends the cover under the site header if it is the first block on the page

### ISSUE THREAD

**Issue by samglover** [samglover/cpt-theme#22]

**Comment by samglover** [comment]
This code is working on a client's site:

`/assets/js/cover-stretch.js`
```js
const siteHeader = document.querySelector('.site-header');
const homeCoverBlock = document.querySelector('.home.has-cover .wp-block-post-content > .wp-block-cover:first-child');
const homeCoverImage = homeCoverBlock.querySelector('.wp-block-cover__image-background');

const objPos = homeCoverImage.style.getPropertyValue('object-position').split(' ');
const objPosX = parseInt(objPos[0].replace('%', ''));
const objPosY = parseInt(objPos[1].replace('%', ''));

function measureHeaderHeight() {
  let headerHeight = siteHeader.offsetHeight;
  document.querySelector(":root").style.setProperty('--header-height', headerHeight + 'px');
  
  if (!homeCoverImage) return;
  let coverImgHeight = homeCoverImage.offsetHeight;
  let newObjPosY = (coverImgHeight * (objPosY / 100) + headerHeight) / (coverImgHeight + headerHeight) * 100;
  homeCoverImage.style.setProperty('object-position', objPosX + '% ' + Math.round(newObjPosY) + '%');
}

window.onload = measureHeaderHeight;
window.onresize = measureHeaderHeight;
```

`/assets/scss/_header.scss`
```scss
.home.has-cover {
  .site-header-primary-nav {
    background-color: $gray-wash;
  }

  .wp-block-post-content {
    > .wp-block-cover:first-child {
      overflow-y: visible;

      .wp-block-cover__background,
      .wp-block-cover__image-background {
        height: calc(100% + var(--header-height));
        top: calc(-1 * var(--header-height));
      }
    }
  }
}
```
