### ISSUE TITLE
Really long words can overflow the post container/page

### ISSUE THREAD

**Issue by samglover** [samglover/cpt-theme#26]
Either select the containers/elements where this can be a problem or solve it generally. Theh CSS code below works, but I'm not sure whether it might have unintended side effects.

```css
.element {
    overflow-wrap: break-word;
    hyphens: auto;
}
```
