### ISSUE TITLE
Add max-width block classes

### ISSUE THREAD

**Issue by samglover** [samglover/cpt-theme#28]
I added these in the child theme for my website, and I think they would be useful utility classes to have generally.

```css
.max-width-sm {
  max-width: $breakpoint-sm !important;
}

.max-width-md {
  max-width: $breakpoint-md !important;
}
```
